<script>
  // Monthly (or all-time) statement for one person, or a summary for everyone in the group.
  import { app, groupName, downloadFile, fileSafe } from '../lib/app.svelte.js';
  import { ledger } from '../lib/ledger.svelte.js';
  import { displayName } from '../lib/engine.js';
  import { buildStatement, monthRange, monthKey, activeMonths, statementText, statementCsv } from '../lib/statement.js';
  import { category } from '../lib/categories.js';
  import { splitTags } from '../lib/tags.js';
  import { money } from '../lib/format.js';
  import { go } from '../lib/router.svelte.js';
  import { toast } from '../lib/toast.svelte.js';
  import Icon from '../components/Icon.svelte';
  import Avatar from '../components/Avatar.svelte';

  let { groupId, query = {} } = $props();

  const me = app.user.email;
  const L = $derived(ledger.current);
  const name = (email) => displayName(email, L.profiles, me);
  const fullName = (email) => L.profiles[email]?.name || email.split('@')[0];

  const months = $derived(activeMonths(L.expenses));
  const month = $derived(query.month || monthKey());
  const person = $derived(query.who || me);
  const members = $derived(Object.keys(L.members).sort((a, b) => (a === me ? -1 : b === me ? 1 : fullName(a).localeCompare(fullName(b)))));

  const range = $derived(month === 'all' ? { from: new Date(0), to: new Date(8640000000000000) } : monthRange(month));
  const period = $derived(month === 'all' ? 'all time' : new Date(range.from).toLocaleDateString(undefined, { month: 'long', year: 'numeric' }));
  const st = $derived(person === '*' ? null : buildStatement(L.expenses, person, range));
  const everyone = $derived(person === '*' ? members.map((m) => ({ m, st: buildStatement(L.expenses, m, range) })) : []);

  const set = (patch) => go(`/g/${groupId}/statement`, { month, who: person, ...patch });
  const signed = (n) => (n > 0.009 ? `+${money(n)}` : n < -0.009 ? `−${money(-n)}` : money(0));
  const tone = (n) => (n > 0.009 ? 'text-emerald-600 dark:text-emerald-400' : n < -0.009 ? 'text-rose-600 dark:text-rose-400' : 'text-slate-400');
  const day = (iso) => new Date(iso).toLocaleDateString(undefined, { day: 'numeric', month: 'short' });
  const describe = (x) =>
    x.type === 'TRANSFER' ? `Payment ${name(x.payer)} → ${name(x.target)}` : x.type === 'LOAN' ? `Loan ${name(x.payer)} → ${name(x.target)}` : splitTags(x.title).text;

  const fmt = $derived({ group: groupName(groupId), person: fullName(person), period, money, name: fullName, date: day });
  const fileBase = $derived(`${fileSafe(groupName(groupId))}_${month}_${fileSafe(person === '*' ? 'everyone' : fullName(person))}`);

  async function share() {
    const text = person === '*'
      ? [`${groupName(groupId)}: balances, ${period}`, '', ...everyone.map(({ m, st }) => `${fullName(m)}: ${signed(st.closing)}`)].join('\n')
      : statementText(st, fmt);
    try {
      if (navigator.share) await navigator.share({ title: `${groupName(groupId)} statement`, text });
      else {
        await navigator.clipboard.writeText(text);
        toast('Statement copied. Paste it in your chat');
      }
    } catch {
      /* share sheet dismissed */
    }
  }

  function csv() {
    if (person === '*') {
      const rows = [['Member', 'Opening', 'Paid', 'Share', 'Payments sent', 'Payments received', 'Closing'].join(',')];
      for (const { m, st } of everyone) rows.push([fullName(m), st.opening, st.totals.paid, st.totals.share, st.totals.sent, st.totals.received, st.closing].map((v) => `"${v}"`).join(','));
      downloadFile(`${fileBase}.csv`, rows.join('\n'));
    } else downloadFile(`${fileBase}.csv`, statementCsv(st, fmt));
  }
</script>

<div class="space-y-5 statement">
  <div class="flex items-center gap-2 no-print">
    <a href="#/g/{groupId}" class="btn btn-ghost !p-2 -ml-2" aria-label="Back"><Icon name="back" /></a>
    <h1 class="text-xl font-black tracking-tight flex-1">Statement</h1>
  </div>

  <div class="grid grid-cols-2 gap-2 no-print">
    <select class="field" value={month} onchange={(e) => set({ month: e.currentTarget.value })} aria-label="Period">
      {#each months as mk (mk)}
        <option value={mk}>{new Date(monthRange(mk).from).toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}</option>
      {/each}
      <option value="all">All time</option>
    </select>
    <select class="field" value={person} onchange={(e) => set({ who: e.currentTarget.value })} aria-label="Person">
      {#each members as m (m)}<option value={m}>{m === me ? `You (${fullName(m)})` : fullName(m)}</option>{/each}
      <option value="*">Everyone</option>
    </select>
  </div>

  <!-- Printed header -->
  <div class="hidden print-only">
    <h1 class="text-2xl font-black">{groupName(groupId)}</h1>
    <p class="text-sm">Statement for {person === '*' ? 'everyone' : fullName(person)}, {period}. Generated by SpreadShare on {new Date().toLocaleDateString()}.</p>
  </div>

  {#if person === '*'}
    <div class="card divide-y divide-slate-100 dark:divide-slate-700/60">
      {#each everyone as { m, st } (m)}
        <a href="#/g/{groupId}/statement?month={month}&who={encodeURIComponent(m)}" class="flex items-center gap-3 px-4 py-3">
          <Avatar email={m} profile={L.profiles[m]} />
          <div class="flex-1 min-w-0">
            <div class="font-semibold text-sm truncate">{name(m)}</div>
            <div class="text-xs text-slate-500">opening {signed(st.opening)} · paid {money(st.totals.paid)} · share {money(st.totals.share)}</div>
          </div>
          <div class="text-right">
            <div class="text-[11px] text-slate-400">closing</div>
            <div class="font-bold tabular-nums {tone(st.closing)}">{signed(st.closing)}</div>
          </div>
        </a>
      {/each}
    </div>
  {:else if st}
    <div class="card p-5 space-y-4">
      <div class="flex items-center gap-3">
        <Avatar email={person} profile={L.profiles[person]} size="w-10 h-10" />
        <div class="flex-1 min-w-0">
          <div class="font-bold truncate">{fullName(person)}</div>
          <div class="text-xs text-slate-500 capitalize">{period}</div>
        </div>
        <div class="text-right">
          <div class="text-[11px] text-slate-400">closing balance</div>
          <div class="text-2xl font-black tabular-nums {tone(st.closing)}">{signed(st.closing)}</div>
        </div>
      </div>
      <dl class="grid grid-cols-2 sm:grid-cols-3 gap-3 text-sm">
        <div><dt class="label !mb-0">Opening</dt><dd class="font-semibold tabular-nums {tone(st.opening)}">{signed(st.opening)}</dd></div>
        <div><dt class="label !mb-0">Paid</dt><dd class="font-semibold tabular-nums">{money(st.totals.paid)}</dd></div>
        <div><dt class="label !mb-0">Share of costs</dt><dd class="font-semibold tabular-nums">{money(st.totals.share)}</dd></div>
        {#if st.totals.sent || st.totals.received}
          <div><dt class="label !mb-0">Payments sent</dt><dd class="font-semibold tabular-nums">{money(st.totals.sent)}</dd></div>
          <div><dt class="label !mb-0">Payments received</dt><dd class="font-semibold tabular-nums">{money(st.totals.received)}</dd></div>
        {/if}
        {#if st.totals.lent || st.totals.borrowed}
          <div><dt class="label !mb-0">Lent / borrowed</dt><dd class="font-semibold tabular-nums">{money(st.totals.lent)} / {money(st.totals.borrowed)}</dd></div>
        {/if}
      </dl>
      <p class="text-xs text-slate-400">Group spent {money(st.totals.spent)} in this period.</p>
    </div>

    {#if st.rows.length === 0}
      <p class="text-sm text-center text-slate-400 py-6">No entries involving {name(person)} in this period.</p>
    {:else}
      <div class="card overflow-hidden">
        <table class="w-full text-sm">
          <thead class="text-[11px] uppercase tracking-wider text-slate-400 text-left">
            <tr class="border-b border-slate-100 dark:border-slate-700/60">
              <th class="px-3 py-2 font-semibold">Date</th>
              <th class="px-3 py-2 font-semibold">Entry</th>
              <th class="px-3 py-2 font-semibold hidden lg:table-cell">Category</th>
              <th class="px-3 py-2 font-semibold text-right hidden sm:table-cell">Paid</th>
              <th class="px-3 py-2 font-semibold text-right hidden sm:table-cell">Share</th>
              <th class="px-3 py-2 font-semibold text-right">Effect</th>
              <th class="px-3 py-2 font-semibold text-right">Balance</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-slate-100 dark:divide-slate-700/60">
            {#each st.rows as r (r.expense.eventId)}
              <tr>
                <td class="px-3 py-2 whitespace-nowrap text-slate-500">{day(r.expense.timestamp)}</td>
                <td class="px-3 py-2 min-w-0">
                  <a href="#/g/{groupId}/e/{r.expense.eventId}" class="block truncate max-w-[10rem] sm:max-w-xs lg:max-w-sm font-medium">{describe(r.expense)}</a>
                  {#if r.expense.type === 'EXPENSE_ADD'}<span class="text-[11px] text-slate-400"><span class="lg:hidden">{category(r.expense.category).label} · </span>{money(r.expense.amount)}</span>{/if}
                </td>
                <td class="px-3 py-2 whitespace-nowrap text-slate-500 hidden lg:table-cell">
                  {#if r.expense.type === 'EXPENSE_ADD'}{category(r.expense.category).icon} {category(r.expense.category).label}{:else}{category('Financial').icon} Payment{/if}
                </td>
                <td class="px-3 py-2 text-right tabular-nums hidden sm:table-cell">{r.paid ? money(r.paid) : ''}</td>
                <td class="px-3 py-2 text-right tabular-nums hidden sm:table-cell">{r.share ? money(r.share) : ''}</td>
                <td class="px-3 py-2 text-right tabular-nums font-semibold {tone(r.net)}">{signed(r.net)}</td>
                <td class="px-3 py-2 text-right tabular-nums text-slate-500">{signed(r.balance)}</td>
              </tr>
            {/each}
          </tbody>
        </table>
      </div>
    {/if}
  {/if}

  <div class="grid grid-cols-3 gap-2 no-print">
    <button class="btn btn-soft" onclick={share}><Icon name="share" class="w-4 h-4" /> Share</button>
    <button class="btn btn-soft" onclick={csv}><Icon name="download" class="w-4 h-4" /> CSV</button>
    <button class="btn btn-soft" onclick={() => window.print()}><Icon name="sheet" class="w-4 h-4" /> PDF</button>
  </div>
  <p class="text-xs text-center text-slate-400 no-print">“PDF” opens your browser’s print dialog. Choose “Save as PDF”.</p>
</div>
